<a href="https://colab.research.google.com/github/monk1108/deep_learning/blob/master/basic_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Assuming that we are on a CUDA machine, this should print a CUDA device:

print(device)

cuda:0


In [ ]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [ ]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

y = w * x + b
y.backward()
print(x.grad)
print(w.grad)
print(b.grad.numpy())

tensor(2.)
tensor(1.)
1.0


In [ ]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2)
print("w :", linear.weight)
print("b :", linear.bias)

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

pred = linear(x)
loss = criterion(pred, y)
print("loss :", loss.item())

loss.backward()
print("dL/dw :", linear.weight.grad)
print("dL/db :", linear.bias.grad)

optimizer.step()  #Performs a single optimization step.

pred = linear(x)
loss = criterion(pred, y)
print("new loss :", loss.item())  #Returns the value of this tensor as a standard Python number. 
                                  #This only works for tensors with one element. 

w : Parameter containing:
tensor([[-0.5379,  0.0522, -0.3252],
        [ 0.4041, -0.4210,  0.3711]], requires_grad=True)
b : Parameter containing:
tensor([ 0.2984, -0.2453], requires_grad=True)
loss : 2.017289161682129
dL/dw : tensor([[-0.9210, -0.5519, -1.5822],
        [ 1.1887,  0.5276,  1.0942]])
dL/db : tensor([ 1.0222, -0.5672])
new loss : 1.9392200708389282


In [ ]:
#loading data from numpy
x = np.array([[1, 2], [3, 4]])
y = torch.from_numpy(x)
z = y.numpy()
print(x)
print(y)
print(z)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [ ]:
# Download and construct CIFAR-10 dataset.
train_dataset = torchvision.datasets.CIFAR10(root='../../data', train=True, transform=transforms.ToTensor(), \
                                             download=True)
image, label = train_dataset[0]
print(image.size())
print(label)

Extracting ../../data/cifar-10-python.tar.gz to ../../data
torch.Size([3, 32, 32])
6


In [ ]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=64, shuffle=True)
data_iter = iter(train_loader)
images, labels = data_iter.next()  #获取下一条数据
for images, labels in train_loader:
  pass

In [ ]:
#Pretrained model
resnet = torchvision.models.resnet18(pretrained=True)

# If you want to finetune only the top layer of the model, set as below.    
for param in resnet.parameters():
  param.requires_grad = False

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth


In [ ]:
# Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)

# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print(outputs.size())

torch.Size([64, 100])


In [ ]:
# Save and load the entire model.
torch.save(resnet, 'model.ckpt')  #.ckpt文件保存了weight, bias和其它变量
model = torch.load('model.ckpt')

# Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

<All keys matched successfully>